### PR TITLE
fix app properties variable name

### PR DESCRIPTION
**Pull request by tynanford**
Hi Han,

This fixes a variable naming issue in application.properties.in that I introduced in my last merge request

### CODE REVIEW

**Comment by jeonghanlee** [comment]
@tynanford , that is not your, but mine. I changed them in order to keep similar conventions compared to others. Please check configuration file as below:

https://github.com/ChannelFinder/ChannelFinder-env/blob/be4d2fcfd557d404c1c672ca53cebce1f041bcc6/configure/CONFIG_SITE#L16-L18

**Comment by tynanford** [comment]
The problem was that I had changed this line in make.conf to match. I think having SSHKEY is fine for applications.properties.in

https://github.com/ChannelFinder/ChannelFinder-env/blob/be4d2fcfd557d404c1c672ca53cebce1f041bcc6/configure/RULES_SRC#L57

`	$(QUIET)sed -e "s:@SSHKEY@:$(CF_SSHKEY):g" \
		    -e "s:@SSHKEYALIAS@:$(CF_SSHKEYALIAS):g" \
		    -e "s:@CFLDIF@:$(CF_LDIF):g" \
		    -e "s:@CF_PORT@:$(CF_PORT):g" \
		    -e "s:@ES_HOST@:$(ES_HOST):g" \
		    -e "s:@ES_PORT@:$(ES_PORT):g" \
		    < $(CF_SITE_TEMPLATE_PATH)/application.properties.in > $(CF_SITE_TEMPLATE_PATH)/application.properties`

**Comment by jeonghanlee** [comment]
Oh, I see now.  And I think, it is better to change as blows:
https://github.com/ChannelFinder/ChannelFinder-env/blob/be4d2fcfd557d404c1c672ca53cebce1f041bcc6/configure/RULES_SRC#L57-L59

Your changes are needed to change `CONFIG_SITE` also. Either way is OK.

**Comment by jeonghanlee** [comment]
No, I am wrong. You're right.

**Pull request merged**
